### ISSUE TITLE
Distinguishing between a MAX6675 and a MAX31855 in a same circuit

### ISSUE THREAD

**Issue by renejeanmercier** [RobTillaart/MAX6675#5]
Hello Mr. Tillaart,

"Pull a request" does not seems to work for me. So I am using "Issues" even though it is not an issues but a request. Thank you for your comprehension.

I have one (1) MAX6675 and one (1) MAX31855 in a same circuit. Is there a way, software wise, to peek at each of them and tell which is which ?

Thank you for you help.

Regards, R.J. Mercier

**Comment by RobTillaart** [comment]
Thanks for the question.
Will come back to it later today.

**Comment by RobTillaart** [comment]
There is one difference that come in my mind - (check the datasheet) -the MAX6675 does not do negative temperatures C.

in software you could write a function that uses the library to connect each of them and see if only one gives reasonable values.
Never tried, don't know if there are side effects - you need to check the datasheets for this.

**Comment by renejeanmercier** [comment]
Thank you Mr Tillaart. I will explore that avenue.

If other approach come to your mind, please do not hesitate to come back.

Regards,

René - Jean

Le mer. 2 août 2023 à 05:23, Rob Tillaart ***@***.***> a
écrit :

**Comment by RobTillaart** [comment]
Hi  René - Jean,

First please call me Rob,

I have thought about it and came up with the following code that might help / get you started.

Patch the libraries to make _read() public (.h file), so you can test with that too.

- https://github.com/RobTillaart/MAX31855_RT
- https://github.com/RobTillaart/MAX6675

The following code might give a clue due to differences in default status.
No hardware nearby to verify this idea, but the sketch compiles.

```cpp
//    FILE: detect.ino
//  AUTHOR: Rob Tillaart
// PURPOSE:  detect TC type
//     URL:  

#include "Arduino.h"

#include "MAX6675.h"
#include "MAX31855.h"

const int dataPin   = 7;
const int clockPin  = 6;
const int selectPin = 5;

void setup()
{
  Serial.begin(115200);
  Serial.println(__FILE__);

  Serial.println(is6675(), HEX);
  Serial.println(is31855(), HEX);
}

void loop()
{
}

uint32_t is6675()
{
  MAX6675 tc;
  tc.begin(clockPin, selectPin, dataPin);

  uint32_t stat = tc.read();       //  replace by _read()
  return stat;
}

uint32_t is31855()
{
  MAX31855 tc;
  tc.begin(clockPin, selectPin, dataPin);

  uint32_t stat = tc.read();       //  replace by _read()
  return stat;
}

// -- END OF FILE --
```

**Comment by renejeanmercier** [comment]
Hello Rob,

Unfortunately, I had dismantled my prototype board. I have to reassemble it
(give me a day or two) for that.

But I have a circuit already assembled with two (2) MAX31855. If I run the
following function (modified with the _read()), I get the following result
(see below the function and the results). Hoping that this will give you
ideas of what we look for.

I will get back to you soon with the mix MAX6675 and MAX31855.

Thank you very much for your support.

Regards,

René-Jean


/****************************************************************************************/

/* PROBE THE THERMOCOUPLE(S) (2 MAX) (4 COMBINAISONS) AND LOG ITS/THEIR
PRESENCE        */

/****************************************************************************************/

void Hardware_Layer::checkThermocouplePresence() { // Establish
thermocouple presence. Up to 2 thermocouple via SPI-1

thermocoupleStatus.thermocoupleOneInstalled = (int)ThermocouplePresence
::thermocoupleNone;

thermocoupleStatus.thermocoupleTwoInstalled =
(int)ThermocouplePresence::thermocoupleNone;


int status;

for(;;) {

/*****************************************************/

thermocoupleOne_MAX31855.begin(THERMO_ONE_CS_PORT); // HW SPI initialization

status = thermocoupleOne_MAX31855._read();

DELAY_MS(1000);

Serial.print(F("Status of reading MAX31855 One is : ")); Serial.println(
status);

if (status == STATUS_OK && thermocoupleStatus.thermocoupleOneInstalled == (
int)ThermocouplePresence::thermocoupleNone) {

thermocoupleStatus.thermocoupleOneInstalled = (int)ThermocouplePresence
::thermocoupleOneMAX31855;

Serial.println(F("Thermocouple One is a MAX31855"));

DELAY_MS(2000);

}

/*****************************************************/

thermocoupleTwo_MAX31855.begin(THERMO_TWO_CS_PORT); // HW SPI
initialization

status = thermocoupleTwo_MAX31855._read();

DELAY_MS(1000);

Serial.print(F("Status of reading MAX31855 Two is : ")); Serial.println(
status);

if (status == STATUS_OK && thermocoupleStatus.thermocoupleTwoInstalled == (
int)ThermocouplePresence::thermocoupleNone) {

thermocoupleStatus.thermocoupleTwoInstalled = (int)ThermocouplePresence
::thermocoupleTwoMAX31855;

Serial.println(F("Thermocouple Two is a MAX6675"));

DELAY_MS(2000);

}

/*****************************************************/

thermocoupleOne_MAX6675.begin(THERMO_ONE_CS_PORT); // HW SPI initialization

status = thermocoupleOne_MAX6675._read();

DELAY_MS(1000);

Serial.print(F("Status of reading MAX6675 One is : ")); Serial.println(
status);

if (status == STATUS_OK && thermocoupleStatus.thermocoupleOneInstalled == (
int)ThermocouplePresence::thermocoupleNone) {

thermocoupleStatus.thermocoupleOneInstalled = (int)ThermocouplePresence
::thermocoupleOneMAX6675;

Serial.println(F("Thermocouple One is a MAX6675"));

DELAY_MS(2000);

}

/*****************************************************/

thermocoupleTwo_MAX6675.begin(THERMO_TWO_CS_PORT); // HW SPI initialization

status = thermocoupleTwo_MAX6675._read();

DELAY_MS(1000);

Serial.print(F("Status of reading MAX6675 Two is : ")); Serial.println(
status);

if (status == STATUS_OK && thermocoupleStatus.thermocoupleTwoInstalled == (
int)ThermocouplePresence::thermocoupleNone) {

thermocoupleStatus.thermocoupleTwoInstalled = (int)ThermocouplePresence
::thermocoupleTwoMAX6675;

Serial.println(F("Thermocouple Two is a MAX6675"));

DELAY_MS(2000);

}

Serial.print(F("\n"));

}

}

=============================

Result :

Status of reading MAX31855 One is : 30941904

Status of reading MAX31855 Two is : 31728640

Status of reading MAX6675 One is : 472

Status of reading MAX6675 Two is : 484


Status of reading MAX31855 One is : 30941888

Status of reading MAX31855 Two is : 31728640

Status of reading MAX6675 One is : 472

Status of reading MAX6675 Two is : 484

... and so on


Processor used STM32F401CE

Software tool : vsCode on PlatformIO.

Le mer. 2 août 2023, à 08 h 55, Rob Tillaart ***@***.***> a
écrit :

**Comment by renejeanmercier** [comment]
Hi Rob,

Here we are. Just a few modifications (see below).  I have used SPI
communication; I added function declarations and a delay (required for USB
serial communication settling). And, as per your request, _read() function.
MAX31855 is on port PB1 and MAX6675 is on port PB10 of and STM32F401CC
BlackPill.

Looking forward to your conclusions.

Regards,

René-Jean

====================================

// FILE: detect.ino
// AUTHOR: Rob Tillaart
// PURPOSE: detect TC type
// URL:

#include "Arduino.h"

#include "MAX6675.h"
#include "MAX31855.h"

/* Function Declaration */
uint32_t is6675();
uint32_t is31855();


// const int dataPin = 7;
// const int clockPin = 6;
// const int selectPin = 5;

void setup()
{
Serial.begin(115200);
delay(2000);
Serial.println(__FILE__);

Serial.println(is6675(), HEX);
Serial.println(is31855(), HEX);
}

void loop()
{
}

uint32_t is6675()
{
MAX6675 tc;
tc.begin(PB10);

uint32_t stat = tc._read(); // replace by _read()
return stat;
}

uint32_t is31855()
{
MAX31855 tc;
tc.begin(PB1);

uint32_t stat = tc._read(); // replace by _read()
return stat;
}

// -- END OF FILE --

=======================
Result of platformIO terminal :
--- Terminal on /dev/ttyACM0 | 230400 8-N-1
--- Available filters and text transformations: colorize, debug, default,
direct, hexlify, log2file, nocontrol, printable, send_on_enter, time
--- More details at https://bit.ly/pio-monitor-filters
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H
Disconnected (device reports readiness to read but returned no data (device
disconnected or multiple access on port?))
Reconnecting to /dev/ttyACM0     Connected!
src/main.cpp
360
1941A50
=====================

Le mer. 2 août 2023, à 08 h 55, Rob Tillaart ***@***.***> a
écrit :

**Comment by RobTillaart** [comment]
so the output is 

src/main.cpp
360
1941A50

looks different to me, however you only did half of the tests.
If you swap the devices (or the pins) and do the checks with the wrong device, what is the output then?

|  device  |  is6675  |  is31855  |
|:--------:|:--------:|:---------:|
|  6675    |   360    |     ?     |
|  31855   |    ?     |  1941A50  |

And then you you should interpret the bit patterns

**Comment by renejeanmercier** [comment]
Hi Rob,

Of course! I should have known better.

Here is the program modified and the results with *_read()* and *read()*
functions.

Regards,


René-Jean
=======================================

// FILE: detect.ino
// AUTHOR: Rob Tillaart
// PURPOSE: detect TC type
// URL:

#include "Arduino.h"

#include "MAX6675.h"
#include "MAX31855.h"

/* Function Declaration */
uint32_t is6675(uint32_t );
uint32_t is31855(uint32_t);

/* Macro substitutions */
const uint32_t MAX31855_PORT = PB1;
const uint32_t MAX6675_PORT = PB10;

/*********************************/
void setup()
{
Serial.begin(230400);
delay(2000);

Serial.println(__FILE__);

Serial.print(F("Peeking with _read() function :\n"));
Serial.print(F("MAX6675 with MAX6675 Dvr\t")); Serial.print(F("MAX6675 with
MAX31855 Dvr\t")); Serial.print(F("MAX31855 with MAX31855 Dvr\t")); Serial.
println(F("MAX31855 with MAX6675 Dvr"));
}

/*********************************/
void loop()
{

Serial.print(is6675(MAX6675_PORT), HEX); Serial.print(F("\t\t\t\t"));
delay(220);
Serial.print(is31855(MAX6675_PORT), HEX); Serial.print(F("\t\t\t\t"));
delay(220);

Serial.print(is31855(MAX31855_PORT), HEX); Serial.print(F("\t\t\t\t"));
delay(220);
Serial.print(is6675(MAX31855_PORT), HEX); Serial.print(F("\n"));
delay(1000);

}

/**********************************/
uint32_t is6675(uint32_t port)
{
MAX6675 tc;
tc.begin(port);

uint32_t stat = tc._read(); // replace by _read()
return stat;
}

/**********************************/
uint32_t is31855(uint32_t port)
{
MAX31855 tc;
tc.begin(port);

uint32_t stat = tc._read(); // replace by _read()
return stat;
}

// -- END OF FILE --

==================================================
src/main.cpp
Peeking with _read() function :
MAX6675 with MAX6675 Dvr        MAX6675 with MAX31855 Dvr       MAX31855
with MAX31855 Dvr      MAX31855 with MAX6675 Dvr
350                                               3500350
                      18C19D0                                        18C
350                                               3500350
                      19019D0                                        18C
348                                               3480348
                      18C19D0                                        18C
358                                               3300330
                      18C19D0                                        18C
358                                               3580358
                      18C19D0                                        18C
340                                               3480348
                      18C19C0                                        18C
350                                               3500350
                      18C19C0                                        18C
340                                               3400340
                      18C19C0                                        18C
350                                               3580358
                      18C19C0                                        18C
348                                               3500350
                      18C19C0                                        18C
350                                               3500350
                        18C19C0                                        18C
360                                               3400340
                        18C19C0                                        18C

==================================================
src/main.cpp
Peeking with read() function :
MAX6675 with MAX6675 Dvr        MAX6675 with MAX31855 Dvr       MAX31855
with MAX31855 Dvr      MAX31855 with MAX6675 Dvr
0                                                   0
                              0
        4
0                                                   0
                              0
        4
0                                                   0
                              0
        4
0                                                   0
                              0
        4
0                                                   0
                              0
        4
0                                                   0
                              0
        4
0                                                   0
                              0
        4
0                                                   0
                              0
        4
0                                                   0
                              0
        4
0                                                   0
                              0
        4
0                                                   0
                              0
        4
0                                                   0
                              0
        4

==================================================

Le ven. 4 août 2023, à 06 h 25, Rob Tillaart ***@***.***> a
écrit :

**Comment by RobTillaart** [comment]
Seems that the values are distinct if you read 32 bits ==> is31855() test

**Comment by renejeanmercier** [comment]
Hi Rob,

Sorry for the delay in answering. This is summer in Québec/Canada ... and
summer is short to complete work outside while there is no rain.

That approach does the job!

Thank you so much for your support.

You might want to add to your MAX6675 and MAX31855 examples to help others
faced with the same question/problem.

Regards,


René-Jean
==============================

Le ven. 4 août 2023, à 11 h 49, Rob Tillaart ***@***.***> a
écrit :

**Comment by RobTillaart** [comment]
For now I do not create a separate example for this as this issue stays archived, so people will find it.
When time permits (typical long winter evenings and nights) I might add it.
If your problem is solved, you may close the issue.

**Comment by renejeanmercier** [comment]
Thanh your for all you do for us, ...your users.

Regards, 

René-Jean
